name: "CI Template"

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Baixando o código fonte
        uses: actions/checkout@v4

      - name: Instalando o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalando dependências
        run: npm ci

      - name: Executando os testes
        run: npm test

      - name: Fazendo upload do relatório de testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/
          if-no-files-found: warn
